FROM python:3.8-alpine


RUN apk update

# install sqlite and dev libs
RUN apk add --no-cache postgresql-libs sqlite && \
 apk add --no-cache --virtual .build-deps gcc libffi-dev musl-dev postgresql-dev


# Copy files
COPY . /backend

WORKDIR /backend

# Install pip reqs
RUN pip install -r /backend/requirements/dev.txt

# Set env variables
ENV FLASK_HOST="0.0.0.0"
ENV FLASK_APP="/backend/autoapp.py"
ENV FLASK_DEBUG=True

EXPOSE 5000

ENTRYPOINT [ "flask", "run", "--with-threads", "--host=0.0.0.0" ]
